### ISSUE TITLE
Backend: Allow topping a minimum of 10 sats + verify user

### ISSUE THREAD

**Issue by handsomelatino** [utxo-one/bitcoiners-network#58]
# Behavior:

Calling the `/transaction/deposit` endpoint with less than 100 sats amount throws error

# Expected:

Allow topping a minimum of 10 sats to allow user verification. If user is not verified bitcoiner, set his type after topup.

**Comment by utxo-one** [comment]
Closed in #59 

Moving the verified logic to #67
